"""Regressions for the 22 findings that survived the adversarial review.

Each test names the concrete failure it prevents. These are the bugs that were
in the shipped artifact, not hypotheticals — if one of these starts failing,
something real broke.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from brownsync_ingest.campus.aliases_parse import parse_aliases, resolve_label
from brownsync_ingest.campus.arcgis import load_arcgis_geojson, normalize_features
from brownsync_ingest.campus.conflate import conflate, load_seed_places
from brownsync_ingest.campus.height import aspect_max_floors, estimate_height, floors_from_area
from brownsync_ingest.campus.job import RANK_MIN_ZOOM, build_document, run_campus_buildings_job
from brownsync_ingest.campus.landmarks import (
    dedupe_labels,
    Landmark,
    load_landmarks,
    names_agree,
)


@pytest.fixture(scope="module")
def buildings():
    rows, _ = normalize_features(load_arcgis_geojson())
    return rows


@pytest.fixture(scope="module")
def places(repo_root):
    return load_seed_places(repo_root / "db/seeds/places.ndjson")


class TestGatesFailClosed:
    def test_a_gate_failure_reaches_the_caller(self, tmp_path: Path, repo_root) -> None:
        # The campus runner used to return JobOutcome(artifacts=(), items=0) on
        # gate failure, so _run_job saw gate_failures=() and printed
        # "[campus] ok: 0 items", exited 0, and `run all` then republished
        # manifest.json at a fresh generation. A drop that failed every gate was
        # indistinguishable from a green run at the exit-code level.
        result = run_campus_buildings_job(
            seeds_dir=tmp_path,  # no places.ndjson, no course_meetings.ndjson
            staging_root=tmp_path / "staging",
            places_path=repo_root / "db/seeds/places.ndjson",
            course_meetings_path=tmp_path / "missing.ndjson",
        )
        assert result.gate_failures, "a missing meetings file must fail a gate"
        assert result.published_count is None, "nothing may publish when a gate fails"
        assert not (tmp_path / "campus_buildings.geojson").exists()

    def test_missing_course_meetings_is_a_gate_not_a_silent_degrade(
        self, tmp_path: Path, repo_root
    ) -> None:
        # meeting_counts returned {} for an absent file, so every gate passed
        # and the good artifact was overwritten with wrong rank/labelMinZoom —
        # 7 buildings dropped out of rank 0 and vanished until z16.5.
        result = run_campus_buildings_job(
            seeds_dir=tmp_path,
            staging_root=tmp_path / "staging",
            places_path=repo_root / "db/seeds/places.ndjson",
            course_meetings_path=tmp_path / "nope.ndjson",
        )
        assert any("meetings" in failure for failure in result.gate_failures)

    def test_an_empty_building_set_reports_the_gate_not_a_traceback(self) -> None:
        # build_document did max(...) over an empty sequence and raised
        # ValueError EIGHT LINES BEFORE the MIN_BUILDINGS gate, so the gate
        # written for exactly this input was dead code and the operator got a
        # max() traceback with status=error instead of the gate text.
        with pytest.raises(ValueError):
            # Still raises if called directly — the fix is that the job never
            # calls it before gating.
            build_document((), _EmptyConflation(), {})


class _EmptyConflation:
    by_code: dict[str, str] = {}
    all_places_by_code: dict[str, tuple[str, ...]] = {}


class TestConflationOrdering:
    def test_a_place_takes_its_own_nearest_footprint(self, buildings, places) -> None:
        # Stage 2 was first-come: the umbrella place `vartan-gregorian-quad`
        # found its true nearest (100061, 19.3 m) occupied and took 100036 at
        # 20.7 m, starving `vartan-gregorian-quad-a` whose centroid is 1.0 m
        # from 100036. That place then shipped in unmatched_places, absent from
        # every feature's placeIds, so it could never tint or be clicked.
        result = conflate(buildings, places)
        match = next(
            (m for m in result.matches if m.place_id == "vartan-gregorian-quad-a"), None
        )
        assert match is not None, "vartan-gregorian-quad-a must bind"
        assert match.property_code == "100036"
        assert match.distance_m <= 2.0

    def test_stage_two_is_order_independent(self, buildings, places) -> None:
        # places.ndjson is regenerated by the places job; the binding must not
        # depend on its row order.
        import random

        outcomes = set()
        for seed in range(8):
            shuffled = list(places)
            random.Random(seed).shuffle(shuffled)
            outcomes.add(
                tuple(sorted((m.place_id, m.property_code) for m in conflate(buildings, shuffled).matches))
            )
        assert len(outcomes) == 1, "conflation output depends on input order"


class TestLabelsNeverLeakRawKeys:
    def test_a_comma_separated_alias_key_is_recovered(self) -> None:
        # Real row 100116: "DISPNAME: Stonewall House, ALT ADDRESS: 22
        # Benevolent" — a comma where a semicolon belongs. Splitting only on
        # ";" swallowed the rest into DISPNAME and
        # "Stonewall House, ALT ADDRESS: 22 Benevolent" shipped as a label.
        parsed = parse_aliases("DISPNAME: Stonewall House, ALT ADDRESS: 22 Benevolent")
        assert parsed.values("DISPNAME") == ("Stonewall House",)
        assert any("','" in d or "instead of" in d for d in parsed.diagnostics)

    def test_the_real_row_resolves_to_a_clean_label(self, buildings) -> None:
        row = next(b for b in buildings if b.property_code == "100116")
        assert row.label == "Stonewall House"
        assert ":" not in row.label

    def test_no_published_label_contains_an_alias_key(self, buildings) -> None:
        for building in buildings:
            assert ":" not in building.label, building.property_code

    def test_a_key_that_still_slips_through_is_stripped(self) -> None:
        result = resolve_label(
            property_code="x",
            property_name="Fallback Hall",
            official_name=None,
            address_line_1=None,
            property_abbr=None,
            parsed=parse_aliases("DISPNAME: Bad Name, LEGACY: Other"),
        )
        assert ":" not in result.label


class TestHeightsArePlausible:
    def test_a_tiny_footprint_cannot_become_a_tower(self) -> None:
        # "Main Accumulation Area Shed": 11 m2 footprint, 1,025 sq ft gross ->
        # ratio 8.56 -> 9 floors -> 32.7 m, the joint second-tallest structure
        # on campus, rendered as a 3.3 m x 3.3 m column beside the SciLi.
        assert aspect_max_floors(118) <= 2  # 118 sq ft ~ 11 m2
        assert floors_from_area(1025, 118) <= 2

    def test_the_real_shed_is_short(self, buildings) -> None:
        shed = next(b for b in buildings if b.property_code == "100237")
        assert shed.height_m < 12, f"{shed.label} is {shed.height_m} m"

    def test_the_default_is_also_aspect_clamped(self) -> None:
        # 19 sub-80 m2 structures took the 3-floor default and became 11.7 m
        # pillars; an 8 m2 pump shed is 2.8 m across.
        tiny = estimate_height(gross_area=None, footprint_area=86)  # ~8 m2
        assert tiny.floors == 1

    def test_a_real_tall_building_is_unaffected(self, buildings) -> None:
        scili = max(buildings, key=lambda b: b.height_m)
        assert "Sciences Library" in scili.label
        assert scili.height_m > 45

    def test_only_genuinely_large_buildings_exceed_thirty_metres(self, buildings) -> None:
        for building in buildings:
            if building.height_m > 30:
                square_metres = (building.footprint_area or 0) / 10.7639
                assert square_metres > 400, f"{building.label} is {building.height_m} m"


class TestLandmarkNaming:
    @pytest.mark.parametrize(
        ("a", "b", "expected"),
        [
            # Same type word, shared distinctive word -> same place.
            ("Simmons Quadrangle (Lower Green)", "Ruth J. Simmons Quadrangle", True),
            ("College Green (Main Green)", "The College Green", True),
            # Type words CONTRADICT -> different places, despite sharing a word.
            ("Pembroke Field", "Pembroke Green", False),
            ("Front Green", "The Quiet Green", False),
        ],
    )
    def test_the_type_word_is_the_discriminator(self, a: str, b: str, expected: bool) -> None:
        # Jaccard scores BOTH "Simmons Quadrangle (Lower Green)" vs "Ruth J.
        # Simmons Quadrangle" and "Pembroke Field" vs "Pembroke Green" at 0.33
        # — identical scores, opposite answers. Only the type word separates.
        assert names_agree(a, b) is expected

    def test_the_named_quad_wins_over_an_adjacent_planting_bed(self, places) -> None:
        # Shipped bug: green:129, a 530 m2 bed that happened to contain the
        # curated centroid, carried "Ruth J. Simmons Quadrangle" while green:39
        # — the 3,195 m2 polygon Brown literally named "Simmons Quadrangle
        # (Lower Green)" — shipped beside it with no placeId. Two "Simmons
        # Quadrangle" labels drew ~50 m apart.
        from brownsync_ingest.campus.landmarks import bind_outdoor_places

        bound, _, _ = bind_outdoor_places(load_landmarks(), places)
        simmons = [b for b in bound if b.place_id == "ruth-j-simmons-quadrangle"]
        assert len(simmons) == 1
        assert simmons[0].id == "green:39"

    def test_no_label_is_published_twice(self) -> None:
        # "Pembroke Field" shipped on two overlapping polygons ~35 m apart,
        # both rank 0 with an identical sortKey 0.0 — no tiebreak, so MapLibre
        # flickered between them on pan.
        deduped = dedupe_labels(load_landmarks())
        labels = [landmark.name for landmark in deduped if landmark.name]
        assert len(labels) == len(set(labels))

    def test_dedupe_keeps_the_larger_polygon_and_its_geometry(self) -> None:
        big = {"type": "Polygon", "coordinates": [[[0, 0], [2, 0], [2, 2], [0, 2], [0, 0]]]}
        small = {"type": "Polygon", "coordinates": [[[0, 0], [1, 0], [1, 1], [0, 1], [0, 0]]]}
        out = dedupe_labels(
            [
                Landmark("a", "green", "Pembroke Field", small, 0.5, 0.5),
                Landmark("b", "field", "Pembroke Field", big, 1.0, 1.0),
            ]
        )
        by_id = {landmark.id: landmark for landmark in out}
        assert by_id["b"].name == "Pembroke Field"
        assert by_id["a"].name is None
        assert by_id["a"].geometry == small  # geometry is never dropped


class TestZoomThresholds:
    def test_label_tiers_are_integers(self) -> None:
        # MapLibre evaluates ["zoom"] inside a FILTER at the integer tile zoom,
        # so 14.5/15.5/16.5 silently rounded UP to 15/16/17: rank 1 was hidden
        # until z16 and rank 2 until z17, leaving 94 buildings labelled only
        # between 17.0 and MAX_ZOOM 17.5.
        for rank, zoom in RANK_MIN_ZOOM.items():
            assert zoom == int(zoom), f"rank {rank} threshold {zoom} is fractional"

    def test_rank_zero_defers_to_the_layer_minzoom(self) -> None:
        # 0 means "as soon as the layer draws" — the layer's own minzoom is
        # fractional-aware, unlike the filter.
        assert RANK_MIN_ZOOM[0] == 0

    def test_the_published_artifact_agrees(self, repo_root) -> None:
        document = json.loads((repo_root / "db/seeds/campus_buildings.geojson").read_text())
        for feature in document["features"]:
            threshold = feature["properties"]["labelMinZoom"]
            assert threshold == int(threshold)
            assert RANK_MIN_ZOOM[feature["properties"]["rank"]] == threshold
